// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventDecoderClient is the client API for EventDecoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventDecoderClient interface {
	SayHello(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
}

type eventDecoderClient struct {
	cc grpc.ClientConnInterface
}

func NewEventDecoderClient(cc grpc.ClientConnInterface) EventDecoderClient {
	return &eventDecoderClient{cc}
}

func (c *eventDecoderClient) SayHello(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cortex.EventDecoder/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventDecoderServer is the server API for EventDecoder service.
// All implementations must embed UnimplementedEventDecoderServer
// for forward compatibility
type EventDecoderServer interface {
	SayHello(context.Context, *Event) (*Response, error)
	mustEmbedUnimplementedEventDecoderServer()
}

// UnimplementedEventDecoderServer must be embedded to have forward compatible implementations.
type UnimplementedEventDecoderServer struct {
}

func (UnimplementedEventDecoderServer) SayHello(context.Context, *Event) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedEventDecoderServer) mustEmbedUnimplementedEventDecoderServer() {}

// UnsafeEventDecoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventDecoderServer will
// result in compilation errors.
type UnsafeEventDecoderServer interface {
	mustEmbedUnimplementedEventDecoderServer()
}

func RegisterEventDecoderServer(s grpc.ServiceRegistrar, srv EventDecoderServer) {
	s.RegisterService(&EventDecoder_ServiceDesc, srv)
}

func _EventDecoder_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventDecoderServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.EventDecoder/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventDecoderServer).SayHello(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// EventDecoder_ServiceDesc is the grpc.ServiceDesc for EventDecoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventDecoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.EventDecoder",
	HandlerType: (*EventDecoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _EventDecoder_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
